### PR TITLE
fix:  async fiber exception message typo

### PR DESCRIPTION
**Pull request by joshamaju**
Fixed typo in async fiber error message.

### CODE REVIEW

**Comment by IMax153** [comment]
Hey @joshamaju ! Thanks for the PR! 

Could you please run pnpm changeset in the root of the repo and document your changes? We use changesets for automatic change log management and such.

Thank you again!

**Comment by joshamaju** [comment]
@IMax153 I can't find any `pnpm changeset` in the package.json. But there's a `version` command

**Comment by IMax153** [comment]
@joshamaju - have you run a `pnpm install` first? `changesets` is included as a `devDependency` in the project:

image

**Comment by joshamaju** [comment]
Thanks for the help

**Comment by IMax153** [comment]
Thanks @joshamaju !

**Pull request merged**
