### PR TITLE
feat(Schedule): added type classes

### PR DESCRIPTION
**Pull request by jessekelly881**
Added type classes for Schedule module.

### CODE REVIEW

**Comment by mikearnaldi** [comment]
The `Foldable` instance is wrong, it happens to compile due to a TS bug (unknown to us prior to this PR): https://twitter.com/MichaelArnaldi/status/1670715270845935616

cc @gcanti

**Comment by jessekelly881** [comment]
Ooh. Interesting. I'll remove the foldable instance then.

**Comment by jessekelly881** [comment]
Ooh. Interesting. Definitely didn't notice the weird TS behavior. I'll remove the foldable instance.

**Comment by gcanti** [comment]
Closing this as the typeclasses have been moved to their own package.

**Pull request closed without merging**
