### PR TITLE
feat: add Logger.set combinator

### PR DESCRIPTION
**Pull request by sukovanej**

### CODE REVIEW

**Comment by sukovanej** [comment]
Yeah, that makes sense. I wanted to create the most direct way to configure logging for probably the most usual use-case - a single logger configured based on the environment. What about I do `setDefault` / `replaceDefault`? That'd introduce the kind of battery I'm looking for as well.

**Comment by IMax153** [comment]
@sukovanej - this is already possible via `Logger.replace(Logger.defaultLogger, myCustomLogger)`. See how we use in the `Logger` module:

https://github.com/Effect-TS/io/blob/3b6fb22acae22645f985af1628ab977e32a7d653/src/Logger.ts#L257

**Comment by sukovanej** [comment]
Yop, I know about that. As I mentioned, this seems like a very usual use-case to me so I thought it would be benefitial to have the most direct way to do it even thought it is already possible with the API in place.

**Comment by mikearnaldi** [comment]
> Yop, I know about that. As I mentioned, this seems like a very usual use-case to me so I thought it would be benefitial to have the most direct way to do it even thought it is already possible with the API in place.

the two are not equivalent one replaces the default logger (replace) this `set` function instead replaces every logger, this will lead to counter intuitive behaviour where one may want to "set" different loggers expecting the result to be logged with every logger

**Pull request closed without merging**
